vmware-samples/euc-samples

- Windows-Samples/Tools & Utilities/SCCM App Migration/Migrate-SCCMApps-AirWatch.ps1
Signed-off-by: Mike Nelson <michaeljr.nelson@gmail.com>
> Added multi app support via gui

- Windows-Samples/Custom Settings/Firewall Rules/AllowAppInbound.xml
- Windows-Samples/Custom Settings/Firewall Rules/README.md
> Add Firewall CSP example allowing an app inbound.

- Windows-Samples/Tools & Utilities/SCCM App Migration/Migrate-SCCMApps-AirWatch.ps1
> Fix bug where selected apps were not being processed.

- Windows-Samples/Custom Settings/Firewall Rules/README.md
> Fixed typo

- Windows-Samples/Custom Settings/Telemetry/Add-TelemetrySettings.xml
- Windows-Samples/Custom Settings/Telemetry/README.md
- Windows-Samples/Custom Settings/Telemetry/Remove-TelemetrySettings.xml
> Add Windows 10 Telemetry Sample.

- Windows-Samples/Tools & Utilities/Software Distribution Staging Scripts/Export-CachedAirWatchApplications.ps1
- Windows-Samples/Tools & Utilities/Software Distribution Staging Scripts/Import-CachedAirWatchApplications.ps1
- Windows-Samples/Tools & Utilities/Software Distribution Staging Scripts/README.MD
> Add SFD staging scripts and Readme

- Windows-Samples/Custom Settings/Firewall Rules/PublicProfileExample.xml
> Add Public profile example

- Windows-Samples/Custom Settings/Firewall Rules/PrivateProfileExample.xml
> Add Private Profile example

- Windows-Samples/Tools & Utilities/SCCM to AirWatch Tag Creation/README.md
- Windows-Samples/Tools & Utilities/SCCM to AirWatch Tag Creation/Tag-SCCM-Collections.ps1
Initial commit of Tag SCCM Collections Script
> Tag sccm collections

- .gitignore
- Windows-Samples/Tools & Utilities/SCCM to AirWatch Tag Creation/Tag-SCCM-Collections.ps1
> Updated Version

- Windows-Samples/Tools & Utilities/SCCM App Migration/Migrate-SCCMApps-AirWatch.ps1
Signed-off-by: Mike Nelson <michaeljr.nelson@vmware.com>
> Fix Issue with fetching App File name from CSV

- Windows-Samples/Tools & Utilities/SCCM App Migration/Migrate-SCCMApps-AirWatch.ps1
> UpdateAppMigration-Fixed UninstallString Detection

- Windows-Samples/Tools & Utilities/SCCM App Migration/Migrate-SCCMApps-AirWatch.ps1
> Update Uninstall Logic

- Windows-Samples/Tools & Utilities/SCCM App Migration/README.md
> Update AppMigration Readme

- Windows-Samples/Tools & Utilities/Change Enrollment User/Change-EnrollmentUser.ps1
- Windows-Samples/Tools & Utilities/Change Enrollment User/README.md
- Windows-Samples/Tools & Utilities/Change Enrollment User/Template.csv
> Add Sample script to update enrollment user from staging user

- Windows-Samples/Custom Settings/MDM over GPO/ControlPolicyConflict.xml
- Windows-Samples/Custom Settings/MDM over GPO/README.md
Signed-off-by: Ameya Jambavalikar <ajambavalikar@vmware.com>
> added Custom Sample XML for MDM vs GPO (ControlPolicyConflict CSP)

- Windows-Samples/Custom Settings/UpdateMgmt/README.md
- Windows-Samples/Custom Settings/UpdateMgmt/UpdateMgmt.xml
Commit 1: added XML to Configure approved updates using GUIDs without having to configure "Active Hours" and other fields that are required in the AW Console
Commit 2: fixed typos in the ReadMe
> Added Custom XML sample for Update Management (Update CSP)

- Windows-Samples/Tools & Utilities/Change Enrollment User/Change-EnrollmentUser.ps1
- Windows-Samples/Tools & Utilities/Change Enrollment User/README.md
Signed-off-by: Mike Nolterieke <mnolterieke@mnolterieke-a01.vmware.com>
> Added ability to pass the path and name of the CSV file via an argument

- Windows-Samples/Custom Settings/Firewall Examples/AllowAppInbound.xml
- Windows-Samples/Custom Settings/Firewall Examples/AllowICMP.xml
- Windows-Samples/Custom Settings/Firewall Examples/PrivateProfileExample.xml
- Windows-Samples/Custom Settings/Firewall Examples/PublicProfileExample.xml
- Windows-Samples/Custom Settings/Firewall Examples/README.md
> Add ICMP example and change folder name

- Windows-Samples/Tools & Utilities/Change Enrollment User/Change-EnrollmentUser.ps1
> Fix issue where multiple migrations fail from a csv

- Windows-Samples/Tools & Utilities/SCCM to AirWatch Auto Registration/README.md
- Windows-Samples/Tools & Utilities/SCCM to AirWatch Auto Registration/Register-SCCM-Devices.ps1
> Update SCCM Registration Script

- macOS-Samples/CustomAttributes/Applications/Tenable/nessus_agent_status.sh
- macOS-Samples/CustomAttributes/Applications/Tenable/nessus_agent_version.sh
- macOS-Samples/CustomAttributes/active_ip_address.sh
- macOS-Samples/CustomAttributes/hostname.sh
- macOS-Samples/CustomAttributes/local_admins.sh
- macOS-Samples/CustomAttributes/openssl_version.sh
- macOS-Samples/CustomAttributes/ssh_version.sh
Includes one to return the active IP address (useful when a machine is on a VPN), SSH version, OpenSSL version, local admin accounts on a machine, and a machines local hostname.
> Adding new custom attributes that we use internally

- Windows-Samples/Tools & Utilities/Deploy LGPO.exe/Deploy-LGPO.ps1
- Windows-Samples/Tools & Utilities/Deploy LGPO.exe/Download-LGPO.ps1
- Windows-Samples/Tools & Utilities/Deploy LGPO.exe/ReadMe.md
Signed-off-by: ajambavalikar <ajambavalikar@vmware.com>
> Deploy LGPO.exe as a managed application

- macOS-Samples/3rd-Party_Software_Guidance/Google Chrome/README.md
- macOS-Samples/3rd-Party_Software_Guidance/Google Chrome/com.google.Chrome.txt
AutoSelectCertificateForUrls support added to documentation after testing in LAB CA.
> Added AutoSelectCertificateForUrls

- macOS-Samples/Privacy Preferences Policy Control/README.md
Signed-off-by: Austin Culter <austinculter@gmail.com>
> Signed-off-by: Austin Culter <austinculter@gmail.com>

- Windows-Samples/Tools & Utilities/Bulk Device Commands/Bulk-DeviceCommand.ps1
- Windows-Samples/Tools & Utilities/Bulk Device Commands/README.md
> Add bulk command script

- Windows-Samples/Tools & Utilities/Bulk Device Commands/README.md
> Fix Readme file

- Windows-Samples/Tools & Utilities/Deploy LGPO.exe/Download-LGPO.ps1
updated LGPO upload script to use correct Modified Date (01/01/2017) for Detection Criteria. Original script used the current date for detection criteria which caused the detection to fail since the modified date for LGPO.exe is 06/01/2017.
> DetectionCriteriaFix

- macOS-Samples/BootstrapPackage/WS1-DEPNotify-Standard/Readme.md
> Updated Readme.md for WS1-DEPNotify-Standard

- macOS-Samples/CustomXMLProfiles/Set_NTP_Server.md
> Added Set_NTP_Server.md

- macOS-Samples/CustomAttributes/LastAppLaunch.md
> Added LastAppLaunch Custom Attribute

- Windows-Samples/Custom Settings/Chrome ADMX/ChromeADMXInstall.xml
- Windows-Samples/Custom Settings/Chrome ADMX/README.md
- Windows-Samples/Custom Settings/Chrome ADMX/SampleChromeSettings.xml
After testing the original sample we had a number of issues getting it working.
The following updates should be a out of the box working sample.
Signed-off-by: Orakel78 <rmyklebust@vmware.com>
> Updated Chrome sample to new working sample

- macOS-Samples/macOS-POC-Guide.md
Adding VMworld 2019 Session Links
> Update POC Guide

- API-Samples/Workspace ONE UEM Samples/UEM Content Sample/PullContent.ps1
- API-Samples/Workspace ONE UEM Samples/UEM Content Sample/README.md
- API-Samples/Workspace ONE UEM Samples/UEM Content Sample/RunParams.json
This sample pull content into a folder based on the category.  Provides a local copy of the files in the content repository.
> Adding sample to download existing content.

- macOS-Samples/CustomXMLProfiles/Notifications.md
> Add more Notifications Settings

- macOS-Samples/3rd-Party_Software_Guidance/Google Chrome/README.md
> Update Google Chrome Policies Location

- macOS-Samples/3rd-Party_Software_Guidance/Google Chrome/README.md
- macOS-Samples/3rd-Party_Software_Guidance/Mozilla Firefox/README.md
> Update Chrome and Firefox Guidance

- macOS-Samples/CustomXMLProfiles/Configure VMware Horizon to a Specific Connection Server.md
> Added config for Vmware Horizon on macOS

- macOS-Samples/3rd-Party_Software_Guidance/Microsoft Edge/README.md
> Adding Microsoft Edge for macOS

- macOS-Samples/Tools/Migration-Tool/README.md
> Updated README

- Windows-Samples/Custom Settings/Chrome ADMX/chromehomepage
Signed-off-by: Kelby Mahoney <kmahoney@vmware.com>
> Adding Chrome Home Page ADMX XML for Win10

- macOS-Samples/Privacy Preferences Policy Control/README.md
Change verbs for dumping TCC.db contents.
> Update Readme.md with sqlite3 verbs

- macOS-Samples/Tools/Migration-Tool/README.md
- macOS-Samples/Tools/Migration-Tool/payload/Library/Application Support/VMware/migrator.py
> Bug fixes and Readme updates

- macOS-Samples/CustomXMLProfiles/Configure VMware Horizon to a Specific Connection Server.md
macOS horizon custom XML update
> Horizonupdate

- macOS-Samples/Scripts/ChangeUser/README.md
- macOS-Samples/Scripts/ChangeUser/newUser.sh
- macOS-Samples/Scripts/ChangeUser/oldUser.sh
> macOS Change Local User

- macOS-Samples/3rd-Party_Software_Guidance/Carbon-Black-Defense/Readme.md
> Update KEXT Info

- macOS-Samples/3rd-Party_Software_Guidance/Carbon-Black-Defense/Readme.md
> Update PkgInfo Plist Information

- macOS-Samples/3rd-Party_Software_Guidance/Carbon-Black-Defense/Readme.md
> CBDefense readme update

- macOS-Samples/3rd-Party_Software_Guidance/Microsoft-Defender-ATP/README.md
adding additional values for the 2 payloads
> Adding Kernel Extensions and Privacy Preferences

- CODE-OF-CONDUCT.md
> Adding Code-of-Conduct

- macOS-Samples/BootstrapPackage/WS1-DEPNotify-Standard/Readme.md
> minor DEPNotify update

- macOS-Samples/Tools/Migration-Tool/payload/Library/Application Support/VMware/migrator.py
> changes to support Big Sur

- macOS-Samples/CustomAttributes/macos_cpu_arch.sh
New sensor/attribute to detect CPU architecture
> macOS cpu sensor

- macOS-Samples/BootstrapPackage/README.md
Updating the image paths in the README so that they properly render on GitHub.
> Updating image paths

- Windows-Samples/Tools & Utilities/Windows 10 App Upload/README.md
- Windows-Samples/Tools & Utilities/Windows 10 App Upload/UploadApp.ps1
- Windows-Samples/Tools & Utilities/Windows 10 App Upload/templates/sample.json
Upload App template script added.
> Add Win10 App Upload script

- macOS-Samples/Tools/app_and_process_details/README.md
- macOS-Samples/Tools/app_and_process_details/appblock.py
Adding a tool to help obtain the needed info about an application to block it with the new app and process blocking functionality in Workspace ONE UEM.
> App process helper

- macOS-Samples/3rd-Party_Software_Guidance/Torii Browser Extension/README.md
Signed-off-by: rterakedis <rterakedis@vmware.com>
> Torii Browser Extension Guidance

- Windows-Samples/Sensors/bios_secure_boot.ps1
- Windows-Samples/Sensors/os_disk_size.ps1
- Windows-Samples/Sensors/system_logicalprocessors.ps1
- Windows-Samples/Sensors/system_totalphysicalmemory.ps1
- Windows-Samples/Sensors/tpm_highest_version.ps1
dashboards and reports
Signed-off-by: Phil Helmling <helmlingp@vmware.com>
> added sensors to assist with Windows 11 Readiness

- macOS-Samples/CustomXMLProfiles/Fall-2021/macOS12_Restrictions.md
The keys incorrectly have "int" as the key name when it should be "integer"
> Fix Integer keys

- UEM-Samples/Utilities and Tools/Generic/UEM API Event Notifications/APIEventNotification.sln
- UEM-Samples/Utilities and Tools/Generic/UEM API Event Notifications/APIEventNotification/.config/dotnet-tools.json
- UEM-Samples/Utilities and Tools/Generic/UEM API Event Notifications/APIEventNotification/APIEventNotification.csproj
- UEM-Samples/Utilities and Tools/Generic/UEM API Event Notifications/APIEventNotification/APIEventNotification.csproj.user
- UEM-Samples/Utilities and Tools/Generic/UEM API Event Notifications/APIEventNotification/Controllers/UEMAPIController.cs
- UEM-Samples/Utilities and Tools/Generic/UEM API Event Notifications/APIEventNotification/Controllers/WebhookController.cs
- UEM-Samples/Utilities and Tools/Generic/UEM API Event Notifications/APIEventNotification/Helpers/Base64.cs
- UEM-Samples/Utilities and Tools/Generic/UEM API Event Notifications/APIEventNotification/Program.cs
- UEM-Samples/Utilities and Tools/Generic/UEM API Event Notifications/APIEventNotification/Startup.cs
- UEM-Samples/Utilities and Tools/Generic/UEM API Event Notifications/APIEventNotification/appsettings.Development.json
- UEM-Samples/Utilities and Tools/Generic/UEM API Event Notifications/APIEventNotification/appsettings.json
- UEM-Samples/Utilities and Tools/Generic/UEM API Event Notifications/APIEventNotification/obj/APIEventNotification.csproj.EntityFrameworkCore.targets
- UEM-Samples/Utilities and Tools/Generic/UEM API Event Notifications/APIEventNotification/obj/APIEventNotification.csproj.nuget.dgspec.json
- UEM-Samples/Utilities and Tools/Generic/UEM API Event Notifications/APIEventNotification/obj/APIEventNotification.csproj.nuget.g.props
- UEM-Samples/Utilities and Tools/Generic/UEM API Event Notifications/APIEventNotification/obj/APIEventNotification.csproj.nuget.g.targets
- UEM-Samples/Utilities and Tools/Generic/UEM API Event Notifications/APIEventNotification/obj/project.assets.json
- UEM-Samples/Utilities and Tools/Generic/UEM API Event Notifications/APIEventNotification/obj/project.nuget.cache
Creating initial version of UEM API Event Notification sample for Feb 2022 content
> UEM API Event Notification sample

- UEM-Samples/Utilities and Tools/Generic/App Upload/README.md
- UEM-Samples/Utilities and Tools/Generic/App Upload/Templates/sample.json
- UEM-Samples/Utilities and Tools/Generic/App Upload/UploadApp.ps1
- AppUpload.ps1 v1.1 to support optional local and remote app icons by using the uploadblob API. Additional comments throughout the script included.
- Updated README to show tested against current UEM version (21.11)
- sample.json re-ordered slightly to have all details properties grouped together
> UploadApp.ps1 version 1.1 changes

- UEM-Samples/Utilities and Tools/Generic/Pagination Recursion Sample/PaginationRecursion.ps1
- UEM-Samples/Utilities and Tools/Generic/Pagination Recursion Sample/README.md
Adding PaginationRecursion.ps1 for dev month sample. Will recursively call the GET /api/mdm/devices/extensivesearch API until all pages have been queried
> Pagination Recursion example

- UEM-Samples/Utilities and Tools/Generic/Pagination Recursion Sample/PaginationRecursion.ps1
Updated comment to reflect maximum pagesize = 500
> PaginationRecursion.ps1 Comment update

- Android-Samples/ReferenceApplications/WS1-Profile-CustomSettings-Android-Reference-App/WS1-Profile.xml
- Android-Samples/ReferenceApplications/WS1-Profile-CustomSettings-Android-Reference-App/app/build.gradle
- Android-Samples/ReferenceApplications/WS1-Profile-CustomSettings-Android-Reference-App/readme.md
Profile included additional, unnecessary, brackets {}
> Updated profile.xml example

- UEM-Samples/Apps/macOS/CrowdStrike Falcon/Falcon Profile.mobileconfig
- UEM-Samples/Apps/macOS/CrowdStrike Falcon/README.md
Adding CrowdStrike Falcon to the macOS Apps section
> CrowdStrike - macOS Apps

- UEM-Samples/Apps/macOS/Arctic Wolf Agent/README.md
Added new app (Arctic Wolf) to macOS/Apps section
> macOS arctic wolf

- UEM-Samples/Profiles/iOS/Fall-2022/iOS16_Restrictions.md
- UEM-Samples/Profiles/macOS/Fall-2022/macOS13_Restrictions.md
Signed-off-by: Paul Evans <paulevans@pevans-a02.vmware.com>
> Restrictions XML for iOS 16 and macOS 13

- UEM-Samples/Utilities and Tools/macOS/Migration-Tool/Migration-Tool-Monterey/scripts/preinstall
preinstall script to install Hub to ensure python3 is installed
> Mac Monterey migrator update

- UEM-Samples/Utilities and Tools/macOS/Migration-Tool/Migration-Tool-Monterey/build-info.json
- UEM-Samples/Utilities and Tools/macOS/Migration-Tool/Migration-Tool-Monterey/payload/Library/Application Support/VMware/migrator.py
- UEM-Samples/Utilities and Tools/macOS/Migration-Tool/Migration-Tool-Monterey/scripts/preinstall
Added the PreInstall script to update the certificates in Python so that the environments are trusted.   Also some other code changes to get everything working.
> Updated with new Preinstallscript

- UEM-Samples/Utilities and Tools/macOS/macOS Updater Utility/README.md
updating links for macOS Updater Utility
> updater updates

- UEM-Samples/Utilities and Tools/macOS/Migration-Tool/Migration-Tool-Monterey/payload/Library/Application Support/VMware/migrator.py
Updated migrator.py with additional check for hub before installing and a fix for loading mobileconfig
> Updated migrator.py with additional check

- UEM-Samples/Profiles/macOS/Fall-2022/macOS_Login_and_Background_Item_Management.md
Signed-off-by: Paul Evans <paulevans@pevans-a02.vmware.com>
> Add macOS 13 Login Items

- UEM-Samples/Profiles/iOS/Fall-2022/iOS16_ACMECertificate.md
- UEM-Samples/Profiles/iOS/Fall-2022/iOS16_AccessibilitySettings
- UEM-Samples/Profiles/iOS/Fall-2022/iOS16_Cellular.md
- UEM-Samples/Profiles/iOS/Fall-2022/iOS16_DNSProxy
- UEM-Samples/Profiles/iOS/Fall-2022/iOS16_SharedDeviceConfig
- UEM-Samples/Profiles/iOS/Fall-2022/iOS16_WebContentFilter
Signed-off-by: ADAM HENRY <adamh1@vmware.com>
> iOS 16 updates

- UEM-Samples/Utilities and Tools/macOS/macOS Updater Utility/README.md
- UEM-Samples/Utilities and Tools/macOS/macOS Updater Utility/macOSupdater.sh
- UEM-Samples/Utilities and Tools/macOS/macOS Updater Utility/macOSupdaterSettings.xml
> mUU Updates

- UEM-Samples/Sensors/macOS/Custom Attributes/active_ip_address.sh
Updated Sensor for python3 included with WSONE.  Also requires no file writing.
> Updated Sensor for python3 included with WSONE

- UEM-Samples/Profiles/macOS/Fall-2022/macOS_Login_and_Background_Item_Management.md
Signed-off-by: Paul Evans <paulevans@pevans-a02.vmware.com>
> updated macOS Login Items

- UEM-Samples/Utilities and Tools/macOS/Migration-Tool/migrationToolWS1/payload/Library/Application Support/VMware/migrator.sh
Added the code to use the email or username to create an enrollment token and enroll the device.
Changed the logging function name, so it doesn't conflict with some devices.
Added function to check for DEPNotify if installed in normal Applications directory
Added a timer for DEPNotify to open.
> Updated Migrator script to support enrolling with token

- UEM-Samples/Scripts/macOS/Use hubcli to perform OS Updates.md
Signed-off-by: Paul Evans <paulevans@pevans4MD6R.vmware.com>
> hubcli mdmcommand osupdate

- UEM-Samples/Utilities and Tools/macOS/macOS Updater Utility/README.md
- UEM-Samples/Utilities and Tools/macOS/macOS Updater Utility/macOSupdater.sh
mUU rev10.1 - fix proxy error when proxy not supplied
> mUU rev10.1

- UEM-Samples/Utilities and Tools/macOS/Migration-Tool/migrationToolWS1/payload/Library/Application Support/VMware/migrator.sh
- UEM-Samples/Utilities and Tools/macOS/Migration-Tool/migrationToolWS1/scripts/postinstall
Signed-off-by: Leon Letto <lettol@vmware.com>
> Changes to permissions and logging.

- Intelligence-Samples/Custom Connectors/Atlassian/Atlassian Cloud Sample.postman_collection.json
- Intelligence-Samples/Custom Connectors/CarbonBlack/Carbon Black.postman_collection.json
- Intelligence-Samples/Custom Connectors/Microsoft Teams/Microsoft Teams Sample.postman_collection.json
- Intelligence-Samples/Custom Connectors/PagerDuty/PagerDuty Sample.postman_collection.json
- Intelligence-Samples/Custom Connectors/Salesforce/Salesforce.postman_collection.json
- Intelligence-Samples/Custom Connectors/ServiceNow/ServiceNow Sample.postman_collection.json
- Intelligence-Samples/Custom Connectors/Slack/Slack Sample.postman_collection.json
- Intelligence-Samples/Custom Connectors/Splunk/Splunk Sample.postman_collection.json
- Intelligence-Samples/Custom Connectors/UEM/Custom UEM API Calls.postman_collection.json
- Intelligence-Samples/Custom Connectors/Zendesk/Zendesk Sample.postman_collection.json
- Added id properties for Intelligence postman collections. This is a new requirement for custom connectors after backend update.
- Generate up to date example responses for serviceNow postman collection. The old ones were outdated, causing verification failures.
> Add id to Intelligence postman collections.

- UEM-Samples/Utilities and Tools/macOS/Workspace ONE mobileconfig Importer/README.md
migrating Workspace ONE mobileconfig importer from Vmware flings site into euc-samples
> Workspace ONE mobileconfig importer
